stages:
  - build
  - deploy

variables:
  NODE_ENV: production
  AWS_REGION: ap-northeast-2 # Replace with your AWS region
  S3_BUCKET_NAME: yjk.x2bee.com # Replace with your S3 bucket name
  CLOUDFRONT_DISTRIBUTION_ID: E1P00JGR4VTHX6 # Replace with your CloudFront distribution ID

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - echo "Installing dependencies..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'
  - nvm install 20 # Adjust to your Node.js version
  - nvm use 20
  - npm install -g npm

build:
  stage: build
  script:
    - echo "Installing project dependencies..."
    - npm install
    - echo "Building the Next.js app..."
    - npm run build
    - echo "Exporting static files..."
    - npm run export
  artifacts:
    paths:
      - out/ # Directory containing exported static files

deploy:
  stage: deploy
  dependencies:
    - build
  image: amazon/aws-cli
  script:
    - echo "Deploying to S3..."
    - aws s3 sync out/ s3://yjk.x2bee.com --delete
    - echo "Invalidating CloudFront cache..."
    - aws cloudfront create-invalidation --distribution-id E1P00JGR4VTHX6 --paths "/*"
  only:
    - main
